export enum BankName {
  CIH = 'CIH',
  BMCE = 'BMCE',
  ATTIJARI = 'ATTIJARI',
  CREDIT_AGRICOLE = 'CREDIT_AGRICOLE',
  CERDIT_DU_MAROC = 'CERDIT_DU_MAROC',
  OUMNIA_BANK = 'OUMNIA_BANK',
  BANK_POPULAIRE = 'BANK_POPULAIRE'
}
